language: node_js
node_js:
  - '10.4.0'
branches:
  only:
  - develop
  - master

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then firebase use production && npm run firebase:deploy; elif [ $TRAVIS_BRANCH == "develop" ]; then firebase use default && npm run firebase:deploy; fi