language: node_js
node_js:
  - '10.4.0'
branches:
  only:
  - develop
  - master
  - firebase-dev

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
 - "[[ $TRAVIS_BRANCH == 'master' ]] && firebase use production"
  - npm run firebase:deploy

