language: node_js
node_js:
- '10.4.0'
branches:
  only:
  - develop

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - npm run firebase:deploy --token $FIREBASE_TOKEN

